name: Validate generated JSON

on:
  pull_request:
    paths:
      - "data/*.json"
  workflow_dispatch:

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Parse JSON files
        run: python -m json.tool data/tools.json > /dev/null && python -m json.tool data/updates.json > /dev/null
